// JS'NIN MOBILE, DESKTOP, BACKEND VS. KUTUPHANELERI VARDIR
// EN POPULERLERI JS => USER INTERFACE KUTUPHANESIDIR
// REACT BIR JS KUTUPHANESIDIR.
// FACEBOOK, COK DINAMIK VE AKISKAN VERI SAYFASIYLA UGRASTIGI ICIN SAYFAYI SUREKLI RENDER ILE YORMAMAK ADINA REACT KUTUPHANESINI GELISTIRMIS.
// YANI REACT'IN TEMEL MANTIGI GEREKSIZ RENDER'LARI AZALTMAK VAR
// KENDINE GORE HTML CSS JS'SI OLAN BIR BLOCK'A COMPONENT YAPISI DENIR. ORNEK: HER BIR TWEET ICINDE ACIKLAMA, RESIM, LINK BOLUMLERI OLUYOR VE HER TWEET'TE BU BLOCK KULLANILIYOR.
//INTERVIEW => CLOSURE NEDIR => ?
//MVC KATMANLARI(Model, View, Controller)
//MODEL(DATABASE) VE CONTROLLER KATMANI => BACKEND => API VE GONDERILEN ISTEKLER, BACKEND KSIIMLARI VS.
//VIEW(UI => REACT) KATMANI =>FRONTEND
//INTERVIEW'DE BANKO SORULUR!!!! (SOLID, MVC,SINGLETON PATTERN, DRIVE )
//FRAMEWORK(ANGULAR, VUE, DJANGO) => HERSEY ICINDE HAZIR OLAN, HARICI KUTUPHANEYE GEREK OLMAYAN, YONLENDIRMELI EKOSISTEMDIR. DISINA CIKMAYA IZIN VERMEZ. KUCUK BIR SEY YAPMAK ICIN BILE BIRCOK SEY BILMEK GEREKIR. HATASIZ, BEST PRACTICE KOD YAZDIRMAK ICIN BOYLE

//LIBRARY(REACT) => ONDEN YAZILMIS KODLARI VERIR, ISTEDIGIN GIBI KULLANIRSIN. ESNEK OLMASI AVANTAJDIR.

//REACT => YAZMASI VE OKUNMASI KOLAYDIR. KLASIK JS'YE GORE DAHA HIZLIDIR, DINAMIKTIR.

//JSX = JS + HTML'DEN OLUSAN OZEL BIR SYNTAX DIYEBILIRIZ.

//REACT'TA FUNCTION BASED VE CLASS BASED COMPONENT GENELDE KULLANILIR
//COMPONENT'LERIN JSX KISMI, RETURN OLAN KISIMDIR.

//BANKO!!!!
//REACT VIRTUAL DOM => SANAL OLARAK UZERINDE CALISTIGI DOM OBJESIDIR VE DEGISIKLERI SONRADAN ASIL DOM'A AKTARDIGI ICIN HIZLIDIR, RAM'DE TUTULUR.
//REACT, DOM'UN ANLIK 2 KOPYASINI ALIP BELLEGE KOYUYOR. DOM'DA YAPMAK ILE BELLEKTE YAPMAK ARASINDA HIZ FARKI VAR. ONCE BELLEKTEKILER UZERINDE UPDATE YAPIYOR, SONRA BUNLARI TOPLU OLARAK DOM'A AKTARIYOR(BASH UPDATE). VE TUM DOM'U DEGIL, ILGILI YERLERI AKTARIYOR.

const setTime = () => {
  //! Vanilla JS Element
  const jsElement = `
     <div>
        <h1>Javascript Element</h1>
        <p>${new Date().toLocaleTimeString()}</p>
     </div>
  `;

  document.querySelector(".container-1").innerHTML = jsElement;

  //! React Element without JSX
  const reactElement = React.createElement(
    "div", //EKLENECEK ELEMENT TIPI
    null, //PARAMETRESI
    React.createElement("h1", null, "React"), //CHILDREN KISMI
    React.createElement("p", null, new Date().toLocaleTimeString())
  );
  ReactDOM.render(reactElement, document.querySelector(".container-2"));
};

setInterval(setTime, 1000); //HER 1000MS ICINDE SET.TIME FONK. CAGIRIYOR.
