//JS'NIN MOBILE, DESKTOP, BACKEND VS. KUTUPHANELERI VARDIR
//EN POPULERLERI JS => USER INTERFACE KUTUPHANESIDIR
// REACT BIR JS KUTUPHANESIDIR.
//FACEBOOK, COK DINAMIK VE AKISKAN VERI SAYFASIYLA UGRASTIGI ICIN SAYFAYI SUREKLI RENDER ILE YORMAMAK ADINA REACT KUTUPHANESINI GELISTIRMIS.
//YANI REACT'IN TEMEL MANTIGI GEREKSIZ RENDER'LARI AZALTMAK VAR
//KENDINE GORE HTML CSS JS'SI OLAN BIR BLOCK'A COMPONENT YAPISI DENIR. ORNEK: HER BIR TWEET ICINDE ACIKLAMA, RESIM, LINK BOLUMLERI OLUYOR VE HER TWEET'TE BU BLOCK KULLANILIYOR.
